# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        auth_token_user_provider:
            id: auth_token_user_provider
        anaxago_provider:
            entity:
                class: AnaxagoCoreBundle:User
                property: username

    firewalls:
        api:
            pattern: ^/api/interests
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~

        main:
            provider: anaxago_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
    encoders:
        Anaxago\CoreBundle\Entity\User:
            algorithm: bcrypt