<?php

namespace Anaxago\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
/**
 * InterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $userId
     * @return array
     */
    public function getInterests(int $userId)
    {
        return $this->createQueryBuilder('i')
            ->innerJoin('i.project', 'p')
            ->innerJoin('i.username', 'u')
            ->select('p.title')
            ->addSelect('i.amount')
            ->where('u.id = :user_id')
            ->setParameter('user_id', $userId)
            ->getQuery()
            ->getArrayResult();

    }

}
