<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param float $invested
     * @param int $id
     */
    public function putInvested(float $invested, $project)
    {
        $id = $project->getId();
        $totalInvested = $project->getInvested() + $invested;
        $this->createQueryBuilder('p')
            ->update()
            ->set('p.invested', $totalInvested)
            ->where('p.id = :id')
            ->setParameter(':id', $id)
            ->getQuery()
            ->execute();
        return $totalInvested;
    }
}
